version: "3.5"

services:
  rooster-mml-client:
    image: "ghcr.io/roembol2000/rooster-mml-client:latest"
    restart: unless-stopped
    ports:
      - 12100:80

  rooster-mml-server:
    image: "ghcr.io/roembol2000/rooster-mml-server:latest"
    restart: unless-stopped
    environment:
      - BASE_URL=https://mmlrooster.msa.nl/dagroosters/
      - NODE_ENV=development
      - PORT=80